export const ConfigKeys = {
    wordPatterns: 'localalot.wordPatterns',
    Ghost: {
        enabled: 'localalot.ghost.enabled',
        baseUrl: 'localalot.ghost.baseUrl',
        stops: 'localalot.ghost.stops',
        apiKey: 'localalot.ghost.apiKey',
        model: 'localalot.ghost.model',
        family: 'localalot.ghost.family',
        endpoint: 'localalot.ghost.endpoint',
        contextPlacement: 'localalot.ghost.contextPlacement',
        promptTemplate: 'localalot.ghost.promptTemplate',
        maxOutputTokens: 'localalot.ghost.capabilities.limits.max_output_tokens',
        maxContextWindowTokens: 'localalot.ghost.capabilities.limits.max_context_window_tokens',
        reasoningEffort: 'localalot.ghost.capabilities.supports.reasoning_effort',
        delay: 'localalot.ghost.capabilities.limits.delay',
        presencePenalty: 'localalot.ghost.presencePenalty',
        frequencyPenalty: 'localalot.ghost.frequencyPenalty',
        stream: 'localalot.ghost.stream',
    },
    Nes: {
        enabled: 'localalot.nes.enabled',
        baseUrl: 'localalot.nes.baseUrl',
        apiKey: 'localalot.nes.apiKey',
        model: 'localalot.nes.model',
        family: 'localalot.nes.family',
        endpoint: 'localalot.nes.endpoint',
        maxOutputTokens: 'localalot.nes.capabilities.limits.max_output_tokens',
        maxContextWindowTokens: 'localalot.nes.capabilities.limits.max_context_window_tokens',
        thinking: 'localalot.nes.capabilities.supports.thinking',
        reasoningEffort: 'localalot.nes.capabilities.supports.reasoning_effort',
        suffixOverlapThreshold: 'localalot.nes.suffixOverlapThreshold',
        suffixOverlapType: 'localalot.nes.suffixOverlapType',
        presencePenalty: 'localalot.nes.presencePenalty',
        frequencyPenalty: 'localalot.nes.frequencyPenalty',
        stream: 'localalot.nes.stream',
        nextCursorPredictionEnabled: 'localalot.nes.nextCursorPrediction.enabled',
        nextCursorJumpWithoutEdit: 'localalot.nes.nextCursorPrediction.jumpWithoutEdit',
        mimicGhostTextBehavior: 'localalot.nes.mimicGhostTextBehavior',
        promptTemplate: 'localalot.nes.promptTemplate',
    }
} as const;
